import { ChucVu } from './chuc-vu.model';
import { DanToc } from './dan-toc.model';
import { GioiTinh } from './gioi-tinh.model';
import { KhoiLop } from './khoi-lop.model';
import { LoaiNhanSu } from './loai-nhan-su.model';
import { PhongBan } from './phong-ban.model';
import { QuocGia } from './quoc-gia.model';
import { TonGiao } from './ton-giao.model';
import { TrangThaiLamViec } from './trang-thai-lam-viec.model';
import { TrangThaiTaiKhoan } from './trang-thai-tai-khoan.model';

export interface NhanSu {
  maNhanSu: number;
  ho: string;
  ten: string;
  maGioiTinh: string;
  ngaySinh: Date;
  noiSinh: string | null;
  cmnd: string;
  ngayCap: Date | null;
  maDanToc: string;
  maTonGiao: string;
  maQuocTich: string;
  ngayVaoTruong: Date;
  maPhongBan: number;
  maTrangThaiLamViec: string;
  lyDoThoiViec: string | null;
  ngayCapNhat: Date;
  maLoaiNhanSu: number;
  maChucVu: number | null;
  maKhoiLop: number | null;
  soDienThoai: string | null;
  email: string | null;
  hoKhau: string | null;
  diaChi: string | null;
  hinhAnh: string | null;
  matKhau: string;
  maTrangThaiTaiKhoan: string;

  phongBan: PhongBan;
  loaiNhanSu: LoaiNhanSu;
  chucVu: ChucVu;
  khoiLop: KhoiLop;
  gioiTinh: GioiTinh;
  danToc: DanToc;
  tonGiao: TonGiao;
  quocTich: QuocGia;
  trangThaiLamViec: TrangThaiLamViec;
  trangThaiTaiKhoan: TrangThaiTaiKhoan;
}
